runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind :$PORT --timeout 120

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5

env_variables:
  ENVIRONMENT: "staging"
  PYTHONUNBUFFERED: "1"
  FRONTEND_URL: "https://storage.googleapis.com/referral-app-dev-frontend"

# Replace <PROJECT_ID> with your actual GCP project ID
beta_settings:
  cloud_sql_instances: "<PROJECT_ID>:us-central1:referral-app-dev-db"
